# Generated by Django 5.1.6 on 2025-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interest', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('WD', 'Web Development'), ('DS', 'Data Science')], max_length=50)),
                ('specialization', models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('EC', 'Electronics')], max_length=50)),
                ('residence', models.CharField(choices=[('Hostel', 'Hostel'), ('Day Scholar', 'Day Scholar')], max_length=50)),
            ],
        ),
    ]
